### ISSUE TITLE
ModuleNotFoundError error

### ISSUE THREAD

**Issue by skyme5** [skyme5/instagram-story#3]
When running the program following error was encountered

```
Traceback (most recent call last):
  File "C:\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python310\Scripts\instagram-story.exe\__main__.py", line 4, in <module>
  File "C:\Python\Python310\lib\site-packages\instagram\__init__.py", line 2, in <module>
    from .instagram import Instagram
  File "C:\Python\Python310\lib\site-packages\instagram\instagram.py", line 15, in <module>
    from .utils import dump_text_file
  File "C:\Python\Python310\lib\site-packages\instagram\utils.py", line 7, in <module>
    from jsonschema import validate
ModuleNotFoundError: No module named 'jsonschema'
```

**Comment by skyme5** [comment]
Fixed
